version: '3.4'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
  dev-app:
    build:
      context: .
      dockerfile: Dockerfile_dev
      target: runner
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    volumes:
      - ./intl:/app/intl
      - ./node_modules:/app/node_modules
      - ./public:/app/public
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./next.config.js:/app/next.config.js
      - ./tsconfig.json:/app/tsconfig.json
  proxy:
    build:
      context: nginx
    ports:
      - "8080:8080"
    environment:
      PROXY_DOMAIN: app:3000
  dev-proxy:
    build:
      context: nginx
    ports:
      - "8080:8080"
    environment:
      PROXY_DOMAIN: dev-app:3000
  local-proxy:
    build:
      context: nginx
    ports:
      - "8080:8080"
    environment:
      PROXY_DOMAIN: localhost:3000
    network_mode: host